# https://dev.classmethod.jp/articles/add-vs-code-remote-development-settings-to-existing-docker-environment/

version: "3.7"
services:
  python-gui:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.wslg
    restart: always
    tty: true
    volumes:
      - ../:/home/user/code
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
